LF-7230-4: ov2775: fix build break on isp-vvcam kernel module with the latest 6.x kernel
Coping with upstream commit ed5c2f5fd10d ("i2c: Make remove callback return void")
int (*remove)(struct i2c_client *client) is replaced by void (*remove)(struct i2c_client *client)

Build error:
vvcam/v4l2/sensor/ov2775/ov2775_mipi_v3.o vvcam/v4l2/sensor/ov2775/ov2775_mipi_v3.c:1792:19: error: initialization of 'void (struct i2c_client *)' \
		from incompatible pointer type 'int (struct i2c_client *)' [-Werror=incompatible-pointer-types] 1792 | .remove = ov2775_remove,
	^~~~~~~~~~~~~ vvcam/v4l2/sensor/ov2775/ov2775_mipi_v3.c:1792:19: note: (near initialization for 'ov2775_i2c_driver.remove')
cc1: all warnings being treated as errors

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>