LF-8716-4: Fix VVCAM kernel ar1335 module's build errors
Fix ar1335 i2c build issue caused by API change.

Caused by:
03c835f498b5 ("i2c: Switch .probe() to not take an id parameter")

~/verisilicon_sw_isp_vvcam/vvcam/v4l2/sensor/ar1335/ar1335_mipi_v3.o
~/verisilicon_sw_isp_vvcam/vvcam/v4l2/sensor/ar1335/ar1335_mipi_v3.c:1241:19:
error: initialization of int (*)(struct i2c_client *) from incompatible pointer
type int (*)(struct i2c_client *, const struct i2c_device_id *) [-Werror=incompatible-pointer-types]
 1241 |         .probe  = ar1335_probe,
      |                   ^~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:68: all] Error 2

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>