LF-9945 capture: vvcam: fix build errors after rebasing to next-20230804
Fix video.c build issues caused by API change.

The issues was introduced since the upstream commits:
adb2dcd5f2d4 ("media: v4l: async: Rename v4l2_async_subdev as
		v4l2_async_connection")
46a7c0f662e1 ("media: v4l: async: Set v4l2_device and subdev
		in async notifier init")
7a2259fc5182b ("media: v4l: async: Rename V4L2_ASYNC_MATCH_ macros,
		add TYPE_")

Build error logs:
verisilicon_sw_isp_vvcam/vvcam/v4l2/video/video.c:1795:18: error:
initialization of int (*)(struct v4l2_async_notifier *,
struct v4l2_subdev *, struct v4l2_async_connection *)
from incompatible pointer type int (*)(struct v4l2_async_notifier *,
struct v4l2_subdev *, struct v4l2_async_subdev *)
[-Werror=incompatible-pointer-types]
 1795 |         .bound = viv_notifier_bound,
      |                  ^~~~~~~~~~~~~~~~~~
verisilicon_sw_isp_vvcam/vvcam/v4l2/video/video.c:1795:18: note:
(near initialization for sd_async_notifier_ops.bound)
verisilicon_sw_isp_vvcam/vvcam/v4l2/video/video.c: In function
viv_find_compatible_nodes: verisilicon_sw_isp_vvcam/vvcam/v4l2/video/
video.c:1944:57: error: V4L2_ASYNC_MATCH_FWNODE undeclared (first use
in this function); did you mean V4L2_ASYNC_MATCH_TYPE_FWNODE?
nodes[cnt].match_type = V4L2_ASYNC_MATCH_FWNODE;
                         ^~~~~~~~~~~~~~~~~~~~~~~
                         V4L2_ASYNC_MATCH_TYPE_FWNODE
verisilicon_sw_isp_vvcam/vvcam/v4l2/video/video.c:1944:57: note: each
undeclared identifier is reported only once for each function it appears
in verisilicon_sw_isp_vvcam/vvcam/v4l2/video/video.c: In function
viv_video_probe: verisilicon_sw_isp_vvcam/vvcam/v4l2/video/video.c:2041:
25: error: too few arguments to function v4l2_async_nf_init
      |                         v4l2_async_nf_init(&vdev->subdev_notifier);
      |                         ^~~~~~~~~~~~~~~~~~
In file included from ../include/media/v4l2-subdev.h:14,
                 from ../include/media/v4l2-device.h:13,
                 from /home/nxf75284/verisilicon_sw_isp_vvcam/vvcam/v4l2/
video/video.c:60:
../include/media/v4l2-async.h:159:6: note: declared here
  159 | void v4l2_async_nf_init(struct v4l2_async_notifier *notifier,
      |      ^~~~~~~~~~~~~~~~~~
verisilicon_sw_isp_vvcam/vvcam/v4l2/video/video.c:2062:64: error:
invalid application of sizeof to incomplete type
struct v4l2_async_subdev
                      sizeof(struct v4l2_async_subdev));
                                ^~~~~~
verisilicon_sw_isp_vvcam/vvcam/v4l2/video/video.c:2086:48: error:
invalid application of sizeof to incomplete type
struct v4l2_async_subdev
        sizeof(struct v4l2_async_subdev));
                  ^~~~~~
verisilicon_sw_isp_vvcam/vvcam/v4l2/video/video.c:2105:57: error:
passing argument 1 of v4l2_async_nf_register from incompatible pointer
type [-Werror=incompatible-pointer-types]
rc = v4l2_async_nf_register(vdev->v4l2_dev,
                           ~~~~^~~~~~~~~~
                             struct v4l2_device *
../include/media/v4l2-async.h:281:56: note: expected
struct v4l2_async_notifier * but argument is of type
struct v4l2_device * int v4l2_async_nf_register(
struct v4l2_async_notifier *notifier);
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
verisilicon_sw_isp_vvcam/vvcam/v4l2/video/video.c:2105:30: error:
too many arguments to function v4l2_async_nf_register
 2105 |                         rc = v4l2_async_nf_register(vdev->v4l2_dev,
      |                              ^~~~~~~~~~~~~~~~~~~~~~
../include/media/v4l2-async.h:281:5: note: declared here
  281 | int v4l2_async_nf_register(struct v4l2_async_notifier *notifier);
      |     ^~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>