LF-8716-1: Fix VVCAM kernel ov2775 module's build errors
Fix ov2775 i2c build issue caused by API change.

Caused by:
03c835f498b5 ("i2c: Switch .probe() to not take an id parameter")

kernel rebase the api change leaded this build error:
~/verisilicon_sw_isp_vvcam/vvcam/v4l2/sensor/ov2775/ov2775_mipi_v3.c:1803:19:
error: initialization of int (*)(struct i2c_client *) from incompatible pointer
type int (*)(struct i2c_client *, const struct i2c_device_id *) [-Werror=incompatible-pointer-types]

 1803 |         .probe  = ov2775_probe,
      |                   ^~~~~~~~~~~~
cc1: all warnings being treated as errors

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>