MA-20991 vvcam build error based on 6.1 kernel
Build error as below:
os08a20_mipi_v3.c:863:13: error: stack frame size (4112) exceeds
limit (2048) in 'os08a20_priv_ioctl' [-Werror,-Wframe-larger-than]

Root Cause:
Clang is upgraded for 6.1 kernel compared to 5.15, more strict on stack frame size.
Also the commit "change VVCAM_SUPPORT_MAX_MODE_COUNT to 20" enlarge the size of below.
  typedef struct vvcam_mode_info_array_s {
  	uint32_t count;
  	struct vvcam_mode_info_s modes[VVCAM_SUPPORT_MAX_MODE_COUNT];
  } vvcam_mode_info_array_t;

Resolution:
Add and use macro USER_TO_KERNEL_VmALLOC/KERNEL_TO_USER__VMALLOC.

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>