LF-8716-2: Fix VVCAM kernel os08a20 module's build errors
Fix os08a20 i2c build issue caused by API change.

Caused by:
03c835f498b5 ("i2c: Switch .probe() to not take an id parameter")

build error log:
~/verisilicon_sw_isp_vvcam/vvcam/v4l2/sensor/os08a20/os08a20_mipi_v3.c:1408:19: error:
initialization of int (*)(struct i2c_client *)from incompatible pointer type
int (*)(struct i2c_client *, const struct i2c_device_id *) [-Werror=incompatible-pointer-types]
 1408 |         .probe  = os08a20_probe,
      |                   ^~~~~~~~~~~~~

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>