LF-8716-5: Fix VVCAM kernel dw9790 module's build errors
Fix dw9790 i2c build issue caused by API change.

Caused by:
03c835f498b5 ("i2c: Switch .probe() to not take an id parameter")

Build error log:
~/verisilicon_sw_isp_vvcam/vvcam/v4l2/focus/vcm_dw9790/dw9790.c:424:19: error:
initialization of int (*)(struct i2c_client *) from incompatible pointer type
int (*)(struct i2c_client *, const struct i2c_device_id *) [-Werror=incompatible-pointer-types]
  424 |         .probe  = dw9790_probe,
      |                   ^~~~~~~~~~~~
~//verisilicon_sw_isp_vvcam/vvcam/v4l2/focus/vcm_dw9790/dw9790.c:424:19: note:
(near initialization for dw9790_i2c_driver.<anonymous>.probe)
cc1: all warnings being treated as errors
make: *** [Makefile:68: all] Error 2

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>