LF-9664: capture: vvcam: fix build vvcam treat the warnings as errors
The change from "CONFIG_VIDEOBUF2_DMA_CONTIG=y" to
"CONFIG_VIDEOBUF2_DMA_CONTIG=m" exposes this build issue, all warnings
will be treated as errors, if the API is defined but not used, it will be
treated as errors. This patch will fix that whenever the macro
CONFIG_VIDEOBUF2_DMA_CONTIG=y or m the build will be successful and the
code is valid.

Build error logs:
/vvcam/v4l2/../isp/isp_isr.c: In function 'isp_hw_isr':
/vvcam/v4l2/../isp/isp_isr.c:273:26: error: unused variable 'frameendmask'
 [-Werror=unused-variable] static const u32 frameendmask =
MRV_MI_MP_FRAME_END_MASK |
/vvcam/v4l2/../isp/isp_isr.c: At top level:
/vvcam/v4l2/../isp/isp_isr.c:164:13: error: 'isr_process_frame' defined
but not used [-Werror=unused-function]
static void isr_process_frame(struct isp_ic_dev *dev)
cc1: all warnings being treated as errors
make[3]: *** [vvcam/v4l2] Error 2
make[2]: *** [kernel-source/Makefile:234: __sub-make] Error 2

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>