LF-7297: basler: fix build break on basler kernel module with the kernel 6.x kernel
Coping with upstream changes:
commit cd75981ec93a ("media: v4l2-ctrls: drop 'idx' argument from control type ops.")

Build error:
vvcam/v4l2/sensor/camera-proxy-driver/basler-camera-driver-vvcam/basler-camera-driver-vvcam.c:731:17: error: initialization of 'void (*)(const struct v4l2_ctrl *, u32,  union v4l2_ctrl_ptr)' {aka 'void (*)(const struct v4l2_ctrl *, unsigned int,  union v4l2_ctrl_ptr)'} from incompatible pointer type 'void (*)(const struct v4l2_ctrl *, u32,  u32,  union v4l2_ctrl_ptr)' {aka 'void (*)(const struct v4l2_ctrl *, unsigned int,  unsigned int, union v4l2_ctrl_ptr)'} [-Werror=incompatible-pointer-types]
  731 |         .init = basler_camera_init,
      |                 ^~~~~~~~~~~~~~~~~~
vvcam/v4l2/sensor/camera-proxy-driver/basler-camera-driver-vvcam/basler-camera-driver-vvcam.c:731:17: note: (near initialization for 'basler_camera_ctrl_type_ops.init')
vvcam/v4l2/sensor/camera-proxy-driver/basler-camera-driver-vvcam/basler-camera-driver-vvcam.c:732:18: error: 'basler_camera_equal' undeclared here (not in a function); did you mean 'basler_camera_dev'?
  732 |         .equal = basler_camera_equal,
      |                  ^~~~~~~~~~~~~~~~~~~
      |                  basler_camera_dev
vvcam/v4l2/sensor/camera-proxy-driver/basler-camera-driver-vvcam/basler-camera-driver-vvcam.c:748:1: error: expected identifier or '(' before '{' token
  748 | {
      | ^
vvcam/v4l2/sensor/camera-proxy-driver/basler-camera-driver-vvcam/basler-camera-driver-vvcam.c:746:12: error: 'basler_camera_validate' declared 'static' but never defined [-Werror=unused-function]
  746 | static int basler_camera_validate(const struct v4l2_ctrl *ctrl, union v4l2_ctrl_ptr ptr);
      |            ^~~~~~~~~~~~~~~~~~~~~~
vvcam/v4l2/sensor/camera-proxy-driver/basler-camera-driver-vvcam/basler-camera-driver-vvcam.c:773:13: error: 'basler_camera_equal' defined but not used [-Werror=unused-function]
  773 | static bool basler_camera_equal(const struct v4l2_ctrl *ctrl, u32 idx, union v4l2_ctrl_ptr ptr1, union v4l2_ctrl_ptr ptr2 )
      |             ^~~~~~~~~~~~~~~~~~~

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>