LF-7230-1: dw9790: fix build break on isp-vvcam kernel module with the latest 6.x kernel
Coping with upstream commit ed5c2f5fd10d ("i2c: Make remove callback return void")

init (*remove)(struct i2c_client *client) is replaced by void (*remove)(struct i2c_client *client)

Build error:
verisilicon_sw_isp_vvcam/vvcam/v4l2/focus/vcm_dw9790/dw9790.c:417:19: error: initialization of ‘void (struct i2c_client *)’ from incompatible pointer type ‘int (struct i2c_client *)’ [-Werror=incompatible-pointer-types]
      417 |         .remove = dw9790_remove,
          |                   ^~~~~~~~~~~~~
    verisilicon_sw_isp_vvcam/vvcam/v4l2/focus/vcm_dw9790/dw9790.c:417:19: note: (near initialization for ‘dw9790_i2c_driver.remove’)

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>