LF-7230-3: basler: fix build break on isp-vvcam kernel module with the latest 6.x kernel
Coping with upstream commit ed5c2f5fd10d ("i2c: Make remove callback return void"),
and commit ab36c1cc3074 ("media: v4l2-ctrls: optimize type_ops for arrays")

kernel rebase the api change leaded this build error
1. int (*remove)(struct i2c_client *client) is replaced by void (*remove)(struct i2c_client *client)
2. void (*init)(const struct v4l2_ctrl *ctrl, u32 from_idx, union v4l2_ctrl_ptr ptr) is replaced by
   void (*init)(const struct v4l2_ctrl *ctrl, u32 from_idx, u32 tot_elems,
                       union v4l2_ctrl_ptr ptr)

Build error:
vvcam/v4l2/sensor/camera-proxy-driver/basler-camera-driver-vvcam/basler-camera-driver-vvcam.c:80:13: error: ‘basler_camera_init’ used but never defined [-Werror]
	vvcam/v4l2/sensor/camera-proxy-driver/basler-camera-driver-vvcam/basler-camera-driver-vvcam.c:744:13: error: ‘basler_camera_init’ defined but not used [-Werror=unused-function]
744 | static void basler_camera_init(const struct v4l2_ctrl *ctrl, u32 idx, u32 tot_elems, union v4l2_ctrl_ptr ptr )
	|             ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>