LF-6890: media: isp: fix build error due to API renamed
Fix VSI video driver build error due to API renamed in bellow commit:

vvcam/v4l2/video/video.c:324:23: error: implicit declaration of function 'media_entity_remote_pad'; did you mean 'media_entity_remove_links'? [-Werror=implicit-function-declaration]

build   17-Aug-2022 16:04:36   |   324 |                 pad = media_entity_remote_pad(pad);

build   17-Aug-2022 16:04:36 vvcam/v4l2/video/video.c:324:21: error: assignment to 'struct media_pad *' from 'int' makes pointer from integer without a cast [-Werror=int-conversion]

(b2e44430b634 media: mc-entity: Rename media_entity_remote_pad() to
     media_pad_remote_pad_first())

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>